version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_quanlymuavu
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: trithong
      MYSQL_DATABASE: quanlymuavu
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
